name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Build geosite
        id: build
        run: |
          go run -v .
      - name: Move and zip files and generate sha256 hash
        run: |
          $(cd rule-set && tar --sort=name --mtime='1970-01-01 00:00:00Z' -cf ../rules.tar *.srs)
          sha256sum rules.tar > rules.tar.sha256sum
      - name: Release rule sets
        if: steps.build.outputs.skip != 'true'
        run: |
          cd rule-set || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ steps.build.outputs.tag }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
      - name: Release geosite
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            rules.tar
            rules.tar.sha256sum
